/**
 *
 */
package eg.java.net.web.jspx.ui.pages;

/**
 * Portlet pages are pages generated by users and can be reused.
 * implementing one business unit.
 * @author amr.eladawy
 *
 */
public class PortletPage extends Page {
    @Override
    public void renderContent() {
        super.renderContent();
    }
}
